sudo: required

language: node_js
node_js: '8'
cache: yarn

git:
  depth: 3

branches:
  only:
  - master

services:
  - docker

env:
- NODE_ENV=test
- PORT=3000
- JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
- JWT_EXPIRATION_MINUTES=15
- MONGO_URI_TESTS=mongodb://mongodb:27017/express-rest-es2017-boilerplate

script:
- yarn docker:test

# deploy:
# - provider: script
#   script: yarn deploy

after_success: yarn coverage
